# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ar_generate_randomness_cpp <- function(nparticles, datalength, dimension) {
    .Call('CoupledPF_ar_generate_randomness_cpp', PACKAGE = 'CoupledPF', nparticles, datalength, dimension)
}

ar_perturb_randomness_cpp <- function(randomness, rho, dimension) {
    .Call('CoupledPF_ar_perturb_randomness_cpp', PACKAGE = 'CoupledPF', randomness, rho, dimension)
}

ar_rinit_rcpp <- function(nparticles, theta, rand, dimension) {
    .Call('CoupledPF_ar_rinit_rcpp', PACKAGE = 'CoupledPF', nparticles, theta, rand, dimension)
}

ar_rtransition_rcpp <- function(xparticles, theta, time, rand, dimension, A) {
    .Call('CoupledPF_ar_rtransition_rcpp', PACKAGE = 'CoupledPF', xparticles, theta, time, rand, dimension, A)
}

compute_cost1_ <- function(x, y) {
    .Call('CoupledPF_compute_cost1_', PACKAGE = 'CoupledPF', x, y)
}

compute_cost2_ <- function(x, y) {
    .Call('CoupledPF_compute_cost2_', PACKAGE = 'CoupledPF', x, y)
}

cost_matrix_ <- function(x, y) {
    .Call('CoupledPF_cost_matrix_', PACKAGE = 'CoupledPF', x, y)
}

square_cost_matrix_ <- function(x, y) {
    .Call('CoupledPF_square_cost_matrix_', PACKAGE = 'CoupledPF', x, y)
}

indexmatching_cpp <- function(ndraws, w1, w2, uniforms) {
    .Call('CoupledPF_indexmatching_cpp', PACKAGE = 'CoupledPF', ndraws, w1, w2, uniforms)
}

indexmatching_given_cpp <- function(ndraws, w1, w2, uniforms, ancestors_ref) {
    .Call('CoupledPF_indexmatching_given_cpp', PACKAGE = 'CoupledPF', ndraws, w1, w2, uniforms, ancestors_ref)
}

transport_cpp <- function(x1, x2, w1, w2, uniforms, epsilon, desired_alpha) {
    .Call('CoupledPF_transport_cpp', PACKAGE = 'CoupledPF', x1, x2, w1, w2, uniforms, epsilon, desired_alpha)
}

transport_given_cpp <- function(x1, x2, w1, w2, uniforms, epsilon, desired_alpha, ancestors_ref) {
    .Call('CoupledPF_transport_given_cpp', PACKAGE = 'CoupledPF', x1, x2, w1, w2, uniforms, epsilon, desired_alpha, ancestors_ref)
}

create_A_ <- function(alpha, d) {
    .Call('CoupledPF_create_A_', PACKAGE = 'CoupledPF', alpha, d)
}

hilbert_order_ <- function(x) {
    .Call('CoupledPF_hilbert_order_', PACKAGE = 'CoupledPF', x)
}

kalman_loglikelihood_ <- function(parameters, observations) {
    .Call('CoupledPF_kalman_loglikelihood_', PACKAGE = 'CoupledPF', parameters, observations)
}

kalman_filtering_means_ <- function(parameters, observations) {
    .Call('CoupledPF_kalman_filtering_means_', PACKAGE = 'CoupledPF', parameters, observations)
}

kalman_smoothing_means_ <- function(parameters, observations) {
    .Call('CoupledPF_kalman_smoothing_means_', PACKAGE = 'CoupledPF', parameters, observations)
}

one_step_lorenz_vector <- function(xparticles, tstart, tend, h, parameters) {
    .Call('CoupledPF_one_step_lorenz_vector', PACKAGE = 'CoupledPF', xparticles, tstart, tend, h, parameters)
}

lorenz_generate_randomness_cpp <- function(nparticles, datalength) {
    .Call('CoupledPF_lorenz_generate_randomness_cpp', PACKAGE = 'CoupledPF', nparticles, datalength)
}

lorenz_perturb_randomness_cpp <- function(randomness, rho) {
    .Call('CoupledPF_lorenz_perturb_randomness_cpp', PACKAGE = 'CoupledPF', randomness, rho)
}

malikpitt_ <- function(xparticles, weights, u) {
    .Call('CoupledPF_malikpitt_', PACKAGE = 'CoupledPF', xparticles, weights, u)
}

median_rcpp <- function(x) {
    .Call('CoupledPF_median_rcpp', PACKAGE = 'CoupledPF', x)
}

multinomial_resampling_n_ <- function(weights, ndraws) {
    .Call('CoupledPF_multinomial_resampling_n_', PACKAGE = 'CoupledPF', weights, ndraws)
}

rmvnorm <- function(nsamples, mean, covariance) {
    .Call('CoupledPF_rmvnorm', PACKAGE = 'CoupledPF', nsamples, mean, covariance)
}

rmvnorm_transpose <- function(nsamples, mean, covariance) {
    .Call('CoupledPF_rmvnorm_transpose', PACKAGE = 'CoupledPF', nsamples, mean, covariance)
}

rmvnorm_transpose_cholesky <- function(nsamples, mean, cholesky_covariance) {
    .Call('CoupledPF_rmvnorm_transpose_cholesky', PACKAGE = 'CoupledPF', nsamples, mean, cholesky_covariance)
}

dmvnorm <- function(x, mean, covariance) {
    .Call('CoupledPF_dmvnorm', PACKAGE = 'CoupledPF', x, mean, covariance)
}

dmvnorm_transpose <- function(x, mean, covariance) {
    .Call('CoupledPF_dmvnorm_transpose', PACKAGE = 'CoupledPF', x, mean, covariance)
}

dmvnorm_transpose_cholesky <- function(x, mean, cholesky_covariance) {
    .Call('CoupledPF_dmvnorm_transpose_cholesky', PACKAGE = 'CoupledPF', x, mean, cholesky_covariance)
}

one_step_pz_vector <- function(xparticles, alphas, t, parameters) {
    .Call('CoupledPF_one_step_pz_vector', PACKAGE = 'CoupledPF', xparticles, alphas, t, parameters)
}

pz_generate_randomness_cpp <- function(nparticles, datalength) {
    .Call('CoupledPF_pz_generate_randomness_cpp', PACKAGE = 'CoupledPF', nparticles, datalength)
}

pz_perturb_randomness_cpp <- function(randomness, rho) {
    .Call('CoupledPF_pz_perturb_randomness_cpp', PACKAGE = 'CoupledPF', randomness, rho)
}

stochvol_dmeas_ <- function(xparticles, theta, observation, dimension) {
    .Call('CoupledPF_stochvol_dmeas_', PACKAGE = 'CoupledPF', xparticles, theta, observation, dimension)
}

systematic_resampling_n_ <- function(weights, ndraws, u) {
    .Call('CoupledPF_systematic_resampling_n_', PACKAGE = 'CoupledPF', weights, ndraws, u)
}

wasserstein_auto_ <- function(p_, q_, cost_matrix_, epsilon, desired_alpha) {
    .Call('CoupledPF_wasserstein_auto_', PACKAGE = 'CoupledPF', p_, q_, cost_matrix_, epsilon, desired_alpha)
}

